language: node_js

node_js:
  - '10'

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm install -g ipfs-deploy

script: env TRAVIS_BRANCH=$TRAVIS_BRANCH npm run build

cache: npm

deploy:
  - provider: script
    script: ./scripts/deploy-prod.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./scripts/deploy-prod.sh
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
