language: generic
deploy:
  provider: s3
  access_key_id: AKIAIOUNKYRWIP35E4PA
  secret_access_key:
    secure: g8JE8wpGWz595hThBf1ckYxoJvSqyngyEMTrKK/pVwBqV2Ou6dXlfHEgalAQIr/9gAnw8aSg2azMvw+nmC6IYY8428x0keKveDiv6CxkBpDXzNPBuRA/+Rmz8+pZgMUWAmYwUq3qfHbLHodUrcJWQK2zqt/DULDr3G8ZoC90Fls5mMvYOg56Fz/04aS73VTdbqspaMO5GPAStHwR/q3feUiVJay8XMTwOmhXRNnPnEE3yi5tdREMQRDP3GVFqZQCo28om3nHF5IvC4aMTIC0ehPcXCb/crRtSBneUKi3qUoUFYL+KG9BiHPnH1cC4nUY/6OvxwbdaVtMj34pL742np/Fulpxwc0shH043SAMJBgS0N7aJEi9Z5MZIjtcq2vOh6RE82pYEgjzXVxGqC+sRGoIRBiQgR1EYBrsQOE7xd8lLClELchYqbGqU0gYgyxUzO92zjeN7nan69YHVhL8knh5pL9c2IWl9k8/eZyUU1XGRahA6mZJZPZieyEHPHIpbH/ogGLfgbllIUSxaokSWbtjlW7g9udlu2tI5MZ7OXYffk/RF/AxdQZWostVFh5/y+zBGzOUAvZWBpCKG6oPedx66Q9V84DrIrYpTAGHlBiVKokd49BoUpL/J+vdqjkjBf3qCPvCiEErFAamFGr4eFcxqrVZXxaWmnxfAZSFGU8=
  bucket: leapdao.org
  acl: public_read
