language: generic
deploy:
  provider: s3
  access_key_id: AKIAIOUNKYRWIP35E4PA
  secret_access_key:
    secure: qE/O+Uy544gzp2vkT/S3LurLIAbaH4melFdJ9dtFzGv32ZBRMSlZLyG/WJ/1jLrypSN+EtOaer1AAfWMjKhYrnuOqGTv0NaQCmOc1dGmBYQ6BIqpTJn68/Tmuz13FemTRh8PIsJ3PNmysGVQ9iwQCg8bLh8WPD7JELRtEYDyPIxi8CI2g4mi9aXM2EOvvlbEypXrbymOWT89AJuoE4XMIKjFl0slmEDbPROkYqdMsDIBE3zrLRCSlHrShC3VQKP84doM6kOCQQQ+Go6HHFJxOpn1sfTwz42MlPZJaNxZ6o/2wnABioUujqTgmGiaj/L6bvofYuDhufPiKDrVgaP6NMSLAxmlhiGDDuGd1QJ1bWwhSmY7CHOhHiEQy82lvy/bPIhZFQ4VmgUpWEfQ97FrDpog5WWIWmUGuZog6A+ug46+ieHkXWi9+iglduGrz5ylkoHQVA+6Oksci5t/RyV2/VPplDDigDt9oUZIDb0X/6FgqpxEuwsAuZ+Fx3XOVKd1Qlat26ui8dW69CQ1TdlAZsGtflSV4hutvWuiQ6CB/e4suFj+ST9taC7yq2QcIxBm/ilalutVyOlwXjabGwL0oYbh4DfptiXZT326T+GhwBuDC8E25gR2dAu+IEV71/M8LNdDU8gY9uhnfV8RAeMavYtfn0sls20PnAzeAtrCdYM=
  bucket: leapdao.org
